version: 1.0.{build}
image: Visual Studio 2022
branches:
  only:
  - master
skip_non_tags: true
install:
- ps: dotnet tool install paket -g
build_script:
- ps: dotnet run --project ./build/Build.fsproj -t BuildPackage
test: off
artifacts:
- path: nugetpkg/*.nupkg
  name: packages
deploy:
- provider: NuGet
  api_key:
    secure: cZQHzBKSudAXPBbRv1Db9QdWXEmscCXgf7mGgWENygmzN24THva07JpPRtc18sJf
  skip_symbols: true
  artifact: packages