image:
  - Visual Studio 2017

install:
  - dotnet tool install fake-cli -g

-
  branches:
    only:
      - master

  skip_non_tags: true
  build_script:
    - fake build PublishNuget
  test: off
  artifacts:
    - path: nugetpkg\*.nupkg
      name: NuGet

# "fall back" configuration for all other branches
# no "branches" section defined
-
  build_script:
    - fake build BuildPackage
  test: off
  artifacts:
    - path: nugetpkg\*.nupkg
      name: NuGet