image: Visual Studio 2017
version: 1.0.{build}
branches:
  only:
  - master
skip_non_tags: true
install:
- ps: dotnet tool install fake-cli -g
build_script:
- ps: fake build PublishNuget
test: off
artifacts:
- path: nugetpkg\*.nupkg
  name: NuGet
