image: Visual Studio 2017
branches:
  only:
  - master
skip_non_tags: true
install:
- ps: dotnet tool install fake-cli -g
build_script:
- ps: fake build -t BuildPackage
test: off
artifacts:
- path: nugetpkg/*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: ZVtUInEH/ZxA6fWIsFZOE45PALWk84+U/kPqFIVBeREKiMADoEI4FZ/LuOStaLF4
  artifact: nugetpkg\*.nupkg
